### ISSUE TITLE
[Bug]: Completing a roadblock creation task by remote-controlling the HC squad can break Arma

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1964]
**Describe the bug**
There have been a couple of reports of player units being duplicated or stuck in an otherwise broken state when completing a roadblock task by remote-controlling the HC squad.

**To Reproduce**
Not sure yet. Might need a DS.

**Comment by DelanoBrouwer** [comment]
As of September 27th, 2022, unable to reproduce on a dedicated server. Completed outposts and roadblocks at varying distances from the player's original position, including beyond render distance. All outposts and roadblocks completed successfully and without issue.

**Comment by Bob-Murphy** [comment]
resolved

**Comment by jaj22** [comment]
Still happens apparently, just unreliable replication:

Espartero: Test server 1 : 5:28 UTC 1 ; I personally drive a HC squad to a deploy roadblock mission and when control comes back to my player I lose control over command cause I couldnt move or do anything I respawn. I dont respawn and then I abort, now theres no commander and my ghost past version is command.

**Comment by jaj22** [comment]
Closing as probably fixed, no reports since #2745
