### ISSUE TITLE
Kill the traitor auto-win

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#321]
Happens in RHS, reports that it never occurs in vanilla though.

10-20s after generation the mission succeeds. They do NOT kill each other, i checked that. They both spawn on the same side, and said side is correct to the controlling faction.

Possibly found the issue with kill the traitor, not sure why it happens though.
He, and his bodyguard, just despawn.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat 
Update?

**Comment by SonorousMeerkat** [comment]
Not looked into this, it is likely another one for the script-savvy.
(unassigning myself from this)

**Comment by Bob-Murphy** [comment]
Game-Breaking of some sort.
Should be fixed in 2.2

**Comment by wurzel0701** [comment]
> They both spawn on the same side, and said side is correct to the controlling faction.
Seems like the traitor itself is not spawning as it should be 3. Maybe the name in the template is wrong or something, can someone confirm this is still happening with the new templates?

The code itself seems pretty solid, especially as it works in vanilla

**Comment by SonorousMeerkat** [comment]
The model for the traitor himself spawns as he should though... Not known it be 3 for the traitors group.
I have yet to do any occupant/invader templates. so this is not changed atm.

As far as i can/could see when i tested it on making this issue, they are despawning and at that point the mission wins because there is no "alive" traitor unit. This afaik is NOT a template problem.

**Comment by wurzel0701** [comment]
Unassigning myself as it only happens in RHS

**Comment by wurzel0701** [comment]
If I can get a rpt of it, I may be able to figure it out

**Comment by SonorousMeerkat** [comment]
Really easy to replicate, load RHS and ask for an assassination mission.

**Comment by Spoffy** [comment]
Fixed in f4ed54e6b1d07b276865aee1ee66e8b5962383c7 (ignore the badly named commit message).

Issue was a bad classname for NATOOfficer2
